### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SynapseRans** [sn0wfa11/win_enum_local#1]
Running Fast Privilege Escalation Enumeration.
ERROR: The system was unable to find the specified registry key or value.
ERROR: The system was unable to find the specified registry key or value.
ERROR: The system was unable to find the specified registry key or value.

Accesschk v6.10 - Reports effective permissions for securable objects
Copyright (C) 2006-2016 Mark Russinovich
Sysinternals - www.sysinternals.com

Done Processing!

**Comment by sn0wfa11** [comment]
@SynapseRans, thanks for the feedback! These errors occur when the script is querying the registry looking for the "AlwaysInstallElevated" and the "Setup!UnattendedFile" keys and the keys are not present. The script is using the following commands:

```
reg query HKLM\SOFTWARE\Policies\Microsoft\Windows\Installer\AlwaysInstallElevated
reg query HKCU\SOFTWARE\Policies\Microsoft\Windows\Installer\AlwaysInstallElevated
reg query HKLM\System\Setup!UnattendFile
```

If you run these commands manually and the keys are not present you will get the same error.

I'm not overly concerned with masking the errors, if they don't show up you know that you might have a quick route to PE. And system command errors are quite common on PE scripts like this. Linuxprivchecker.py can show similar, Linux-based, system errors if there is no access to certain commands it is trying to run. 

To prevent confusion on these errors in the future, would you like to see the script be more verbose or have more info in the readme or wiki about the potential for similar errors if system commands fail?

**Comment by sn0wfa11** [comment]
Updated README.md to show a note about these errors. Closing this issue.
